import Footer from "@/section/Footer";
import "../styles/globals.css";
import Header from "@/section/Header";
import LenisWrapper from "@/utils/LenisWrapper";
import TransitionProvider from "@/utils/TransitionProvider";

export const metadata = {
  title: "Clikkmaster",
  icons: {
    icon: "/favicon.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LenisWrapper>
          <TransitionProvider>

            {children}
            <Footer />
          </TransitionProvider>
        </LenisWrapper>
      </body>
    </html>
  );
}
